[package]
name = "tfhe"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
